=== ICT-Berufsbildung/rm2012/docs/selfhtml/xml/dtd/anzeige/adressen.dtd
<!ELEMENT adressen (adresse)*>

<!ELEMENT adresse (anrede?, name, (postfach | wohnanschrift), plzort)>

<!ELEMENT anrede (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT postfach (#PCDATA)>
<!ELEMENT wohnanschrift (#PCDATA)>
<!ELEMENT plzort (#PCDATA)>

=== ICT-Berufsbildung/rm2012/docs/selfhtml/xml/dtd/anzeige/adressen.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE adressen SYSTEM "adressen.dtd">
<adressen>
<adresse>
  <name>Wurmstädter Anlagenbank</name>
  <postfach>7001</postfach>
  <plzort>00234 Wurmstadt</plzort>
</adresse>
<adresse>
  <anrede>Herr</anrede>
  <name>Willi Wacholder</name>
  <wohnanschrift>Holzwurmstr. 30</wohnanschrift>
  <plzort>00234 Wurmstadt</plzort>
</adresse>
</adressen>
