=== ICT-Berufsbildung/rm2012/docs/selfhtml/xml/dtd/anzeige/lager.dtd
<!ENTITY % artikel "artikelnummer, artikelname, artikelmenge">
<!ENTITY % zusatz "beschreibung | warenklasse">
<!ELEMENT lager (eingang | ausgang)*>
<!ELEMENT eingang (eingangsnummer, (%artikel;), (%zusatz;))>
<!ELEMENT ausgang (ausgangsnummer, (%artikel;), (%zusatz;))>
<!ELEMENT eingangsnummer (#PCDATA)>
<!ELEMENT ausgangsnummer (#PCDATA)>
<!ELEMENT artikelnummer  (#PCDATA)>
<!ELEMENT artikelname    (#PCDATA)>
<!ELEMENT artikelmenge   (#PCDATA)>
<!ELEMENT beschreibung   (#PCDATA)>
<!ELEMENT warenklasse    (#PCDATA)>

=== ICT-Berufsbildung/rm2012/docs/selfhtml/xml/dtd/anzeige/lager.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE lager SYSTEM "lager.dtd">
<lager>

<eingang>
  <eingangsnummer>452</eingangsnummer>
  <artikelnummer>45-234</artikelnummer>
  <artikelname>Schreibtischstuhl "Chef"</artikelname>
  <artikelmenge>10</artikelmenge>
  <warenklasse>C-III</warenklasse>
</eingang>
<ausgang>
  <ausgangsnummer>318</ausgangsnummer>
  <artikelnummer>37-917</artikelnummer>
  <artikelname>Spiegelschrank  "Narziss"</artikelname>
  <artikelmenge>3</artikelmenge>
  <beschreibung>F-IV</beschreibung>
</ausgang>

</lager>
