=== ICT-Berufsbildung/rm2012/docs/selfhtml/xml/dtd/anzeige/personendatenbank.dtd
<!ELEMENT personendatenbank          (person)*>
<!ELEMENT person          (bio,sozio)>
<!ATTLIST person
   name                   CDATA #REQUIRED
>
<!ELEMENT bio             (augen,haar,haut,gewicht,blutgruppe)>
<!ELEMENT augen           EMPTY>
<!ATTLIST augen
   farbe                  CDATA #REQUIRED
>
<!ELEMENT haar            EMPTY>
<!ATTLIST haar
   farbe                  CDATA #REQUIRED
   bemerkung              CDATA #IMPLIED
>
<!ELEMENT haut            EMPTY>
<!ATTLIST haut
   farbe                  CDATA #REQUIRED
   bemerkung              CDATA #IMPLIED
>
<!ELEMENT gewicht         EMPTY>
<!ATTLIST gewicht
   kg                     CDATA #REQUIRED
>
<!ELEMENT blutgruppe      EMPTY>
<!ATTLIST blutgruppe
   typ                    (A|B|0|AB) #REQUIRED
>
<!ELEMENT sozio           (sprache,stand,passport)>
<!ELEMENT sprache         EMPTY>
<!ATTLIST sprache
   lang                   CDATA #REQUIRED
   kurz                   (de|en|fr|es|pt|it) #IMPLIED
>
<!ELEMENT stand           EMPTY>
<!ATTLIST stand
   typ                    (ledig|verheiratet|verwitwet) #REQUIRED
>
<!ELEMENT passport        EMPTY>
<!ATTLIST passport
   nr                     NMTOKEN #REQUIRED
>

=== ICT-Berufsbildung/rm2012/docs/selfhtml/xml/dtd/anzeige/personendatenbank.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE personendatenbank SYSTEM "personendatenbank.dtd">
<personendatenbank>
<person name="Bruno Buddelmann">
  <bio>
    <augen farbe="graublau" />
    <haar farbe="blond" bemerkung="hin und wieder getönt" />
    <haut farbe="weiß" />
    <gewicht kg="84" />
    <blutgruppe typ="A" />
  </bio>
  <sozio>
    <sprache lang="deutsch" kurz="de" />
    <stand typ="ledig" />
    <passport nr="38385409398" />
  </sozio>
</person>
</personendatenbank>
