=== ICT-Berufsbildung/rm2012/docs/selfhtml/xml/darstellung/anzeige/produktnews.dtd
<!ELEMENT produktnews (#PCDATA | beschreibung)*>
<!ELEMENT beschreibung (#PCDATA | hersteller | produkt | preis)*>
<!ELEMENT hersteller (#PCDATA)>
<!ELEMENT produkt (#PCDATA)>
<!ELEMENT preis (#PCDATA)>

=== ICT-Berufsbildung/rm2012/docs/selfhtml/xml/darstellung/anzeige/produktnews.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE produktnews SYSTEM "produktnews.dtd">
<?xml-stylesheet type="text/xsl" href="produktnews.xsl" ?>
<produktnews>

Die neuesten Produktnachrichten:

<beschreibung>
Die Firma <hersteller>Fridolin Soft</hersteller> hat eine neue Version des
beliebten Ballerspiels <produkt>HitYourStick</produkt> herausgebracht.
Nach Angaben des Herstellers soll die neue Version, die nun auch auf dem
Betriebssystem <produkt>Ganzfix</produkt> läuft, um die <preis>80 Dollar</preis>
kosten.
</beschreibung>

<beschreibung>
Von <hersteller>Ripfiles Inc.</hersteller> gibt es ein Patch zu der Sammel-CD
<produkt>Best of other people's ideas</produkt>. Einige der tollen
Webseiten-Templates der CD enthielten bekanntlich noch versehentlich nicht
gelöschte Angaben der Original-Autoren. Das Patch ist für schlappe
<preis>200 Euro</preis> zu haben.
</beschreibung>

</produktnews>
